name: CNB Exchange Rate

on:
  schedule:
  - cron:  '00 15 * * 1-5'

permissions:
  contents: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create timestamped file
      run: |
         curl -s https://www.cnb.cz/cs/financni-trhy/devizovy-trh/kurzy-devizoveho-trhu/kurzy-devizoveho-trhu/denni_kurz.txt?date=$(date +'%d.%m.%Y') >  exr-$(date '+%Y-%m-%d').txt
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push