name: scheduled action

on:
  schedule:
  - cron:  '*/5 * * * *'

permissions:
  contents: write

jobs:
  action:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'simonw/shot-scraper-template' }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/github-script@v6
      name: Create timestamp file 1
      with:
        script: |
          
    - name: Create timestamp file 2
      run: |
        touch `date +"%FT%H%M%S"`.txt
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
